# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://dirkkalmbach.github.io/dirkiboys_nbdev_on_colab/"

git_url = "https://github.com/dirkkalmbach/dirkiboys_nbdev_on_colab/tree/master/"

def custom_doc_links(name): return None
